Repository cockroachdb/docs, pull requests merged in 2018-03, with the labels that each got.

#2573 Fix new in 2.0 callout
  v2.0/monitoring-and-alerting.md
Labels: in progress

#2571 Link from local orchestration to real orchestration overview
  v1.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
  v1.1/orchestration.md
  v2.0/orchestrate-a-local-cluster-with-kubernetes-insecure.md
  v2.0/orchestration.md
Labels: in progress

#2561 JSONB data type
  _includes/sidebar-data-v2.0.json
  v2.0/data-types.md
  v2.0/inet.md
  v2.0/jsonb.md
Labels: in progress

#2570 Fix ycsb rate limit flag in training
  v1.0/demo-automatic-cloud-migration.md
  v1.1/demo-automatic-cloud-migration.md
  v1.1/training/fault-tolerance-and-automated-repair.md
  v2.0/demo-automatic-cloud-migration.md
Labels: in progress

#2582 Link to company-agnostic training survey
  _includes/sidebar-data-training.json
Labels: in progress

#2584 Change site name to CockroachDB
  _config.yml
Labels: in progress

#2583 Recommend against running Kubernetes instructions from a cloud shell
  _includes/orchestration/monitor-cluster.md
  _includes/orchestration/start-kubernetes.md
Labels: in progress

#2585 Add missing COPY buttons to Kubernetes docs
  _includes/orchestration/start-kubernetes.md
  _includes/orchestration/stop-kubernetes.md
  v1.0/orchestrate-cockroachdb-with-kubernetes.md
  v1.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
  v2.0/orchestrate-a-local-cluster-with-kubernetes-insecure.md
Labels: in progress

#2592 Fix clock synch instructions in on-premises tutorials
  _includes/prod_deployment/synchronize-clocks.md
Labels: in progress

#2593 Tweaks to monitoring docs
  v1.1/monitor-cockroachdb-with-prometheus.md
  v1.1/monitoring-and-alerting.md
  v2.0/monitor-cockroachdb-with-prometheus.md
  v2.0/monitoring-and-alerting.md
Labels: in progress

#2588 Release Notes Draft
  _config.yml
  _data/releases.yml
  releases/v2.0-beta.20180305.md
  v2.0/install-cockroachdb.html
Labels: in progress

#2596 Replace intro training slides with videos
  v1.1/training/architecture-overview.md
  v1.1/training/why-cockroachdb.md
Labels: in progress

#2601 Fix root cert param name in SQL shell example
  v1.0/use-the-built-in-sql-client.md
  v1.1/use-the-built-in-sql-client.md
  v2.0/use-the-built-in-sql-client.md
Labels: in progress

#2605 Add a warning about the JOIN/ORDER BY bug in beta-20180305
  releases/v2.0-beta.20180305.md
Labels: in progress

#2623 Fix explanation of unavailable ranges in admin ui docs
  v1.1/admin-ui-replication-dashboard.md
  v2.0/admin-ui-replication-dashboard.md
Labels: in progress

#2625 Add Range Lease definition to architecture overview
  v1.1/architecture/overview.md
  v2.0/architecture/overview.md
Labels: in progress

#2610 Fix a typo on the 'Distribution Layer' page
  v1.1/architecture/distribution-layer.md
  v2.0/architecture/distribution-layer.md
Labels: in progress

#2613 Fix broken link on 'Storage Layer' page
  v1.1/architecture/storage-layer.md
  v2.0/architecture/storage-layer.md
Labels: in progress

#2600 Doc updates for planned maintenance events
  _includes/faq/planned-maintenance.md
  v1.1/remove-nodes.md
  v2.0/operational-faqs.md
  v2.0/remove-nodes.md
  v2.0/sql-faqs.md
  v2.0/stop-a-node.md
Labels: in progress

#2628 Clarify go version requirement for our load generators
  v1.0/demo-automatic-cloud-migration.md
  v1.1/demo-automatic-cloud-migration.md
  v1.1/demo-follow-the-workload.md
  v2.0/demo-automatic-cloud-migration.md
  v2.0/demo-follow-the-workload.md
Labels: in progress

#2626 Change references to information schema columns from boolean true/false to yes/no.
  v2.0/information-schema.md
Labels: in progress

#2656 Fixed broken openssl docs links
  v1.1/create-security-certificates-openssl.md
  v2.0/create-security-certificates-openssl.md
Labels: in progress

#2633 update DROP INDEX doc
  v2.0/drop-index.md
Labels: in progress

#2619 Add client-side redirect from /training/overview.html to current training home
  v1.1/training/index.md
Labels: in progress

#2621 Fix incorrect SHOW KV TRACE syntax.
  v1.1/show-trace.md
  v2.0/show-trace.md
Labels: in progress

#2631 start a node: add clarification on specifying flags every time
  v1.0/start-a-node.md
  v1.1/start-a-node.md
  v2.0/start-a-node.md
Labels: in progress

#2632 Update documentation for EXPLAIN
  v2.0/explain.md
Labels: in progress

#2637 Add the referential_constraints view to information schema
  v2.0/information-schema.md
Labels: in progress

#2639 Attempt to clarify the node status command's updated_at field
  v1.0/view-node-details.md
  v1.1/view-node-details.md
  v2.0/view-node-details.md
Labels: in progress

#2663 Add information on how to monitor clock offsets to the Operational FAQ
  _includes/faq/clock-synchronization-effects.html
  _includes/faq/clock-synchronization-monitoring.html
  _includes/faq/clock-synchronization_v2.0.html
  v1.1/operational-faqs.md
  v1.1/recommended-production-settings.md
  v2.0/operational-faqs.md
  v2.0/recommended-production-settings.md
Labels: in progress

#2657 Fix the position of some semicolons.
  v2.0/table-expressions.md
Labels: fixitday, in progress

#2641 Fix the intro for table expressions.
  v2.0/table-expressions.md
Labels: fixitday, in progress

#2685 Fix the intro of selection clauses
  v2.0/selection-clauses.md
Labels: fixitday, in progress

#2654 sql: Add missing columns in information_schema.columns view
  v2.0/information-schema.md
Labels: fixitday, in progress, product

#2662 sql: Add missing columns to information_schema.statistics table
  v2.0/information-schema.md
Labels: fixitday, in progress

#2673 sql: Add information_schema.administrable_role_authorizations view
  v2.0/information-schema.md
Labels: in progress

#2675 sql: Add information_schema.column_privileges view
  v2.0/information-schema.md
Labels: in progress

#2643 CONTRIBUTING: suggest checking Allow edits from maintainers
  CONTRIBUTING.md
Labels: fixitday, in progress

#2634 fix typo on errexit sql client option
  v1.1/use-the-built-in-sql-client.md
  v2.0/use-the-built-in-sql-client.md
Labels: in progress

#2677 Document changes to the built-in replication zones
  v2.0/configure-replication-zones.md
Labels: fixitday, in progress

#2642 Clarify ON DATABASE vs ON TABLE.* grants
  v1.0/grant.md
  v1.1/grant.md
  v2.0/grant.md
Labels: fixitday

#2661 Document how to upgrade a cluster on Kubernetes
  _includes/orchestration/kubernetes-upgrade-cluster.md
  v1.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
  v1.1/orchestrate-cockroachdb-with-kubernetes.md
  v2.0/orchestrate-cockroachdb-with-kubernetes-insecure.md
  v2.0/orchestrate-cockroachdb-with-kubernetes.md
Labels: fixitday, in progress

#2665 Admin UI Docs FixItDay
  images/admin_ui_cpu_time_2.0.png
  v2.0/admin-ui-databases-page.md
  v2.0/admin-ui-runtime-dashboard.md
Labels: fixitday

#2638 drop CHECK when column is dropped
  v1.0/check.md
  v1.1/check.md
  v2.0/check.md
  v2.0/drop-column.md
Labels: in progress

#2683 Explain that a node's --host is what it will be named in the Admin UI
  _includes/prod_deployment/insecure-start-nodes.md
  _includes/prod_deployment/secure-start-nodes.md
Labels: fixitday, in progress

#2686 Fix incorrect statement about GCE network load balancing
  v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v1.0/deploy-cockroachdb-on-google-cloud-platform.md
  v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v1.1/deploy-cockroachdb-on-google-cloud-platform.md
  v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v2.0/deploy-cockroachdb-on-google-cloud-platform.md
Labels: fixitday, in progress

#2687 Call out the backend timeout setting of GCE's TCP Proxy load balancers
  v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v1.0/deploy-cockroachdb-on-google-cloud-platform.md
  v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v1.1/deploy-cockroachdb-on-google-cloud-platform.md
  v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v2.0/deploy-cockroachdb-on-google-cloud-platform.md
Labels: fixitday, in progress

#2678 Add copy-clipboard to commands on the Configure Replication Zones page
  v1.0/configure-replication-zones.md
  v1.1/configure-replication-zones.md
  v2.0/configure-replication-zones.md
Labels: fixitday, in progress

#2680 expand the definition of "batches" of statements
  v2.0/transactions.md
Labels: fixitday, in progress

#2684 Add words about read refreshing to the transaction design page
  v2.0/architecture/transaction-layer.md
Labels: fixitday, in progress

#2679 Bump version number in version flag
  v2.0/cluster-setup-troubleshooting.md
  v2.0/known-limitations.md
  v2.0/recommended-production-settings.md
  v2.0/start-a-node.md
Labels: fixitday, in progress

#2693 Try to speed up htmlproofer
  Rakefile
Labels: in progress

#2672 sql: add information_schema.(applicable_roles|enabled_roles) views
  v2.0/information-schema.md
Labels: in progress

#2640 update cloudformation docs with load generator selection instructions
  v1.0/deploy-a-test-cluster.md
  v1.1/deploy-a-test-cluster.md
  v2.0/deploy-a-test-cluster.md
Labels: in progress

#2696 Correct spelling mistake in v2.0 sql-layer.md
  v2.0/architecture/sql-layer.md
Labels: in progress

#2697 Remove K8s scaling instructions for CF template
  v1.1/deploy-a-test-cluster.md
Labels: in progress

#2644 known-limitations: remove incremental-after-schema-change warning
  v2.0/known-limitations.md
Labels: fixitday, in progress

#2702 Remove scaling step for test clustet tutorial
  v1.0/deploy-a-test-cluster.md
  v2.0/deploy-a-test-cluster.md
Labels: in progress

#2700 Use htmltest instead of HTML proofer for faster CI
  .gitignore
  .htmltest.yml
  Gemfile
  Gemfile.lock
  Makefile
  Rakefile
  _config.yml
  _includes/sidebar.html
  ci/Dockerfile
  ci/README.md
  ci/builder
  ci/nightly
  ci/pull-request
  v1.0/install-cockroachdb.html
  v1.0/multi-active-availability.md
  v1.0/sql-grammar.md
  v1.1/multi-active-availability.md
  v1.1/sql-grammar.md
  v2.0/multi-active-availability.md
  v2.0/sql-grammar.md
Labels: in progress

#2698 Use single quotes rather than backticks on field names
  v2.0/jsonb.md
Labels: in progress

#2670 Specify restrictions on the target of `init`
  v1.1/initialize-a-cluster.md
  v2.0/initialize-a-cluster.md
Labels: fixitday, in progress

#2611 Fix Markdown error in unsorted list
  v1.1/architecture/distribution-layer.md
  v2.0/architecture/distribution-layer.md
Labels: in progress

#2682 identify all statements that can be EXPLAINed
  v1.0/explain.md
  v1.1/explain.md
  v2.0/explain.md
Labels: fixitday, in progress

#2707 Fix version switcher URLs
  _includes/sidebar.html
  _plugins/versions/versioned_page.rb
Labels: in progress

#2604 Add release notes for v1.1.6 and v2.0-beta.20180312
  _config.yml
  _data/releases.yml
  _includes/sidebar-data-v1.1.json
  _includes/sidebar-releases.json
  releases/v1.1.6.md
  releases/v2.0-beta.20180312.md
Labels: in progress

#2666 add example to insert on conflict
  v1.1/insert.md
  v2.0/insert.md
Labels: in progress

#2710 Remove withdrawn releases from full release list
  _data/releases.yml
Labels: in progress

#2655 add descriptions of as of system time's benefits/drawbacks
  v2.0/backup.md
  v2.0/performance-best-practices-overview.md
  v2.0/select.md
  v2.0/transactions.md
Labels: in progress

#2711 improve connection instructions for sqlalchemy
  v1.0/build-a-python-app-with-cockroachdb-sqlalchemy.md
  v1.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
  v2.0/build-a-python-app-with-cockroachdb-sqlalchemy.md
Labels: in progress

#2595 Add script that checks for unused images
  images/2grow-to-any-scale.png
  images/CL_Logo_Horizontal.png
  images/CraigIllustration_Marathon.png
  images/SCENE_superhero_profile_craig.png
  images/admin_ui_change_time.png
  images/admin_ui_decommissioned_nodes.png
  images/admin_ui_execution_latency_90_percentile.png
  images/admin_ui_execution_latency_99_percentile.png
  images/admin_ui_live_bytes.png
  images/admin_ui_live_nodes.png
  images/admin_ui_logs.png
  images/admin_ui_nodes_list.png
  images/admin_ui_schema_changes.png
  images/admin_ui_select_node.png
  images/admin_ui_service_latency_90_percentile.png
  images/admin_ui_sql_connections_migration.png
  images/announcement_catrina.png
  images/builder_craig.png
  images/catrina_desk.png
  images/catrina_inspector.png
  images/catrina_ramen-01.png
  images/catrina_ramen.png
  images/cockroach_db.png
  images/craig_crossfit.png
  images/craig_opera.png
  images/craig_tie.png
  images/fireside_catrina.png
  images/footer_logo.png
  images/footer_logo.svg
  images/identify-node-decommission.png
  images/insert_singleton_detail.png
  images/mailinglist-icon.png
  images/ramen_catrina.svg
  images/scientist_catrina.png
  images/sidenav-arrow.svg
  images/sleeping_craig.png
  images/super_profile_catrina.png
  scripts/find-unused-images.py
Labels: in progress

#2586 Update node decommissioning docs for 2.0
  images/cluster-status-after-decommission1.png
  images/cluster-status-after-decommission2.png
  images/decommission-multiple1.png
  images/decommission-multiple6.png
  images/decommission-multiple7.png
  images/remove-dead-node1.png
  v2.0/remove-nodes.md
  v2.0/view-node-details.md
Labels: in progress

#2715 Speed up unused image finding script
  scripts/find-unused-images.py
Labels: in progress

#2618 Update clock offset shutdown language
  v1.1/architecture/transaction-layer.md
  v2.0/architecture/transaction-layer.md
Labels: fixitday, in progress

#2658 Document ORDER BY and row ordering
  _includes/sidebar-data-v2.0.json
  _includes/sql/v2.0/diagrams/col_qualification.html
  _includes/sql/v2.0/diagrams/column_def.html
  _includes/sql/v2.0/diagrams/create_index.html
  _includes/sql/v2.0/diagrams/create_table.html
  _includes/sql/v2.0/diagrams/create_table_as.html
  _includes/sql/v2.0/diagrams/create_view.html
  _includes/sql/v2.0/diagrams/drop_table.html
  _includes/sql/v2.0/diagrams/drop_view.html
  _includes/sql/v2.0/diagrams/family_def.html
  _includes/sql/v2.0/diagrams/index_def.html
  _includes/sql/v2.0/diagrams/insert.html
  _includes/sql/v2.0/diagrams/interleave.html
  _includes/sql/v2.0/diagrams/opt_interleave.html
  _includes/sql/v2.0/diagrams/show_cluster_setting.html
  _includes/sql/v2.0/diagrams/show_create_table.html
  _includes/sql/v2.0/diagrams/show_create_view.html
  _includes/sql/v2.0/diagrams/sort_clause.html
  _includes/sql/v2.0/diagrams/stmt_block.html
  _includes/sql/v2.0/diagrams/table_constraint.html
  _includes/sql/v2.0/diagrams/update.html
  _includes/sql/v2.0/diagrams/upsert.html
  v2.0/create-index.md
  v2.0/create-table-as.md
  v2.0/create-table.md
  v2.0/create-view.md
  v2.0/delete.md
  v2.0/drop-view.md
  v2.0/indexes.md
  v2.0/insert.md
  v2.0/interleave-in-parent.md
  v2.0/query-order.md
  v2.0/select.md
  v2.0/sql-faqs.md
  v2.0/truncate.md
  v2.0/update.md
  v2.0/upsert.md
Labels: fixitday, in progress

#2624 Add daemonization note to cli `--background` flag
  v1.0/start-a-node.md
  v1.1/start-a-node.md
  v2.0/start-a-node.md
Labels: fixitday, in progress

#2725 Add more robots tags to training page headers
  _includes/head.html
Labels: in progress

#2727 Switch install page from .html to .md
  v1.0/install-cockroachdb.md
  v2.0/install-cockroachdb.md
Labels: in progress

#2660 Add disk usage info to '{Start,Secure} Cluster'
  _includes/available-capacity-metric.md
  v1.1/admin-ui-access-and-navigate.md
  v1.1/admin-ui-overview-dashboard.md
  v1.1/admin-ui-storage-dashboard.md
  v1.1/known-limitations.md
  v1.1/secure-a-cluster.md
  v1.1/start-a-local-cluster.md
  v2.0/admin-ui-access-and-navigate.md
  v2.0/admin-ui-overview-dashboard.md
  v2.0/admin-ui-storage-dashboard.md
  v2.0/known-limitations.md
  v2.0/secure-a-cluster.md
  v2.0/start-a-local-cluster.md
Labels: fixitday, in progress

#2704 sql: document SPLIT AT statement
  CONTRIBUTING.md
  _includes/sidebar-data-v2.0.json
  _includes/sql/v2.0/diagrams/split_index_at.html
  _includes/sql/v2.0/diagrams/split_table_at.html
  v1.1/rename-index.md
  v2.0/alter-index.md
  v2.0/alter-table.md
  v2.0/split-at.md
  v2.0/sql-statements.md
Labels: fixitday, in progress

#2676 Improve IMPORT 2.0 Docs
  releases/v1.2-alpha.20171204.md
  releases/v2.0-alpha.20180129.md
  v2.0/import.md
  v2.0/insert.md
  v2.0/performance-best-practices-overview.md
Labels: fixitday

#2732 Clarify where to find docker install guidance
  _includes/start_in_docker/mac-linux-steps.md
  v1.0/start-a-local-cluster-in-docker.md
  v1.1/start-a-local-cluster-in-docker.md
  v2.0/start-a-local-cluster-in-docker.md
Labels: in progress

#2674 updates to the SHOW TRACE FOR docs
  _includes/sql/v2.0/diagrams/show_trace.html
  v2.0/show-trace.md
Labels: fixitday

#2733 Remove "beta" label from IMPORT
  _includes/sidebar-data-v2.0.json
  v2.0/import.md
Labels: in progress

#2608 Inverted Indexes
  v2.0/create-index.md
  v2.0/create-table.md
  v2.0/foreign-key.md
  v2.0/import.md
  v2.0/indexes.md
  v2.0/inverted-indexes.md
  v2.0/performance-best-practices-overview.md
Labels: in progress

#2734 Exclude GitHub link in footer from link checking
  _includes/footer.html
Labels: in progress

#2627 upgrade cockroach version: add version compatibility information
  v1.0/upgrade-cockroach-version.md
  v1.1/upgrade-cockroach-version.md
  v2.0/upgrade-cockroach-version.md
Labels: fixitday, in progress

#2736 Remove new/changed in 1.1 callouts from prominent places
  v2.0/add-column.md
  v2.0/add-constraint.md
  v2.0/alter-column.md
  v2.0/alter-table.md
  v2.0/backup.md
  v2.0/cockroach-commands.md
  v2.0/data-types.md
  v2.0/drop-column.md
  v2.0/drop-constraint.md
  v2.0/information-schema.md
  v2.0/manage-long-running-queries.md
  v2.0/rename-column.md
  v2.0/rename-table.md
  v2.0/restore.md
  v2.0/sql-dump.md
  v2.0/sql-statements.md
Labels: in progress

#2744 Mark JSON as supported in 2.0
  _includes/sidebar-data-v2.0.json
  v2.0/sql-feature-support.md
Labels: in progress

#2745 Correct health?ready=1 example
  v2.0/monitoring-and-alerting.md
Labels: in progress

#2742 JSONB functions and operators
  v2.0/jsonb.md
Labels: in progress

#2671 Update 'Stop a Node' with more draining info
  _includes/settings/v2.0/settings.md
  v1.1/stop-a-node.md
  v2.0/cluster-settings.md
  v2.0/stop-a-node.md
Labels: fixitday, in progress

#2730 Add params and examples to `VALIDATE CONSTRAINT`
  v1.1/validate-constraint.md
  v2.0/validate-constraint.md
Labels: in progress

#2746 Note changed HTML test program
  CONTRIBUTING.md
Labels: in progress

#2717 release notes for v2.0-beta.20180319
  _config.yml
  _data/releases.yml
  releases/v2.0-beta.20180319.md
Labels: in progress

#2748 Reflect the introduction of schemas in the name scheme
  _includes/sidebar-data-v2.0.json
  _includes/sql/v2.0/diagrams/create_inverted_index.html
  _includes/sql/v2.0/diagrams/show_schemas.html
  v2.0/cluster-setup-troubleshooting.md
  v2.0/create-index.md
  v2.0/demo-automatic-rebalancing.md
  v2.0/demo-data-replication.md
  v2.0/demo-fault-tolerance-and-recovery.md
  v2.0/information-schema.md
  v2.0/learn-cockroachdb-sql.md
  v2.0/set-vars.md
  v2.0/show-databases.md
  v2.0/show-schemas.md
  v2.0/show-tables.md
  v2.0/show-vars.md
  v2.0/sql-name-resolution.md
  v2.0/sql-statements.md
  v2.0/table-expressions.md
  v2.0/views.md
Labels: in progress

#2629 add documentation about Snapshots chart on Replication dashboard
  images/admin_ui_replica_snapshots.png
  v1.1/admin-ui-replication-dashboard.md
  v2.0/admin-ui-replication-dashboard.md
Labels: fixitday, in progress

#2753 Update 2.0 full sql grammar page
  _includes/sql/v2.0/diagrams/stmt_block.html
Labels: in progress

#2755 Remove pgweb mention in v2.0-beta.20180319 release notes
  releases/v2.0-beta.20180319.md
Labels: in progress

#2716 add json tutorial
  _includes/json/json-sample.go
  _includes/sidebar-data-v2.0.json
  v2.0/demo-json-support.md
Labels: in progress

#2763 Various JSON and core benefit updates
  v1.1/demo-automatic-cloud-migration.md
  v1.1/demo-automatic-rebalancing.md
  v1.1/demo-data-replication.md
  v1.1/demo-fault-tolerance-and-recovery.md
  v1.1/demo-follow-the-workload.md
  v1.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
  v2.0/demo-automatic-cloud-migration.md
  v2.0/demo-automatic-rebalancing.md
  v2.0/demo-data-replication.md
  v2.0/demo-fault-tolerance-and-recovery.md
  v2.0/demo-follow-the-workload.md
  v2.0/demo-json-support.md
  v2.0/inverted-indexes.md
  v2.0/jsonb.md
  v2.0/orchestrate-a-local-cluster-with-kubernetes-insecure.md
Labels: in progress

#2766 Added pages for enabling node map
  v1.1/enable-node-map.md
  v2.0/enable-node-map.md
Labels: in progress

#2767 Spelling fix in upsert.md
  v1.0/upsert.md
  v2.0/upsert.md
Labels: in progress

#2740 [WIP] Algolia site search
  _includes/head.html
  _includes/sidebar.html
  css/components/_algolia.scss
  css/customstyles.css
  css/customstyles.css.map
  css/customstyles.scss
  images/algolia.svg
  js/algoliasearch.min.js
  js/autocomplete.jquery.min.js
  js/cookieUtils.js
  js/setDocsContext.js
  search.html
Labels: in progress

#2770 Fixing link to training survey
  v1.1/training/locality-and-replication-zones.md
  v2.0/training/locality-and-replication-zones.md
Labels: in progress

#2771 fix broken snippet truncating
  search.html
Labels: in progress

#2754 Release notes draft
  _config.yml
  _data/releases.yml
  _includes/sidebar-releases.json
  releases/v1.1.7.md
  releases/v2.0-beta.20180326.md
Labels: in progress

#2759 Computed Columns
  _includes/computed-columns/jsonb.md
  _includes/computed-columns/partitioning.md
  _includes/computed-columns/secondary-index.md
  _includes/computed-columns/simple.md
  _includes/sidebar-data-v2.0.json
  v2.0/computed-columns.md
  v2.0/create-table.md
  v2.0/inverted-indexes.md
  v2.0/jsonb.md
Labels: in progress

#2777 Pause/Cancel/Resume IMPORT jobs
  _includes/sidebar-data-v1.1.json
  _includes/sidebar-data-v2.0.json
  v1.1/sql-statements.md
  v2.0/cancel-job.md
  v2.0/import.md
  v2.0/pause-job.md
  v2.0/resume-job.md
  v2.0/sql-statements.md
Labels: in progress

#2783 Disallow bulkio statements within transactions
  v2.0/backup.md
  v2.0/import.md
  v2.0/restore.md
Labels: in progress

#2705 Added content for with revision_history and point-in-time restore
  v2.0/backup.md
  v2.0/restore.md
Labels: in progress

#2757 Document per-replica zone configs
  v2.0/configure-replication-zones.md
Labels: in progress

#2482 Added partitioning doc and updated sidebar nav
  _includes/sidebar-data-v2.0.json
  v2.0/partitioning.md
Labels: in progress

#2786 Introduce 2.1 docs alias
  _config.yml
Labels: in progress

#2779 Sequence Updates
  v2.0/backup.md
  v2.0/create-sequence.md
  v2.0/drop-sequence.md
  v2.0/rename-sequence.md
  v2.0/restore.md
  v2.0/sql-dump.md
Labels: in progress

#2787 Partitioning Links
  v2.0/computed-columns.md
  v2.0/partitioning.md
Labels: in progress

#2780 Update CASCADE + CHECK constraints
  v2.0/computed-columns.md
  v2.0/foreign-key.md
Labels: in progress

#2788 Add callouts to Debug Logs pages re: UTC usage
  v1.1/debug-and-error-logs.md
  v2.0/debug-and-error-logs.md
Labels: in progress

#2808 Node Map: Related changes
  images/v2.0/admin-ui-cluster-overview-panel.png
  images/v2.0/admin-ui-node-components.png
  images/v2.0/admin-ui-node-list.png
  images/v2.0/admin-ui-region-component.png
  images/v2.0/admin-ui-single-node.gif
  images/v2.0/admin-ui-time-range.gif
  images/v2.0/cluster-status-after-decommission2.png
  v2.0/admin-ui-access-and-navigate.md
  v2.0/admin-ui-overview.md
Labels: in progress

#2812 Run htmltest on links in the sidebar
  _config.yml
  _includes/sidebar-data-v2.0.json
  _plugins/sidebar_htmltest.rb
Labels: in progress

#2815 Misc 2.0 updates
  _includes/sql/v2.0/functions.md
  _includes/sql/v2.0/operators.md
  v2.0/debug-zip.md
  v2.0/deploy-a-test-cluster.md
  v2.0/install-cockroachdb.md
  v2.0/training/cluster-startup-and-scaling.md
  v2.0/training/node-startup-troubleshooting.md
Labels: in progress

#2790 Reflect some v2.0 changes to the SQL CLI
  v2.0/known-limitations.md
  v2.0/use-the-built-in-sql-client.md
Labels: in progress

#2822 Indicate that limitation is resolved as of 2.0
  v1.0/known-limitations.md
  v1.1/known-limitations.md
Labels: in progress

#2782 Document SQL audit logs, including `EXPERIMENTAL_AUDIT`
  _includes/custom/v2.0/logging-flags.md
  _includes/experimental-warning.md
  _includes/sidebar-data-v2.0.json
  _includes/sql/v2.0/diagrams/experimental_audit.html
  v2.0/alter-table.md
  v2.0/debug-and-error-logs.md
  v2.0/experimental-audit.md
  v2.0/sql-audit-logging.md
  v2.0/start-a-node.md
Labels: in progress

#2816 Improve load balancing docs
  _includes/faq/clock-synchronization-effects.html
  _includes/sidebar-data-v1.1.json
  _includes/sidebar-data-v2.0.json
  v1.0/deploy-cockroachdb-on-aws-insecure.md
  v1.0/deploy-cockroachdb-on-aws.md
  v1.0/deploy-cockroachdb-on-digital-ocean-insecure.md
  v1.0/deploy-cockroachdb-on-digital-ocean.md
  v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v1.0/deploy-cockroachdb-on-google-cloud-platform.md
  v1.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
  v1.0/deploy-cockroachdb-on-microsoft-azure.md
  v1.0/manual-deployment-insecure.md
  v1.0/manual-deployment.md
  v1.1/deploy-cockroachdb-on-aws-insecure.md
  v1.1/deploy-cockroachdb-on-aws.md
  v1.1/deploy-cockroachdb-on-digital-ocean-insecure.md
  v1.1/deploy-cockroachdb-on-digital-ocean.md
  v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v1.1/deploy-cockroachdb-on-google-cloud-platform.md
  v1.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
  v1.1/deploy-cockroachdb-on-microsoft-azure.md
  v1.1/deploy-cockroachdb-on-premises-insecure.md
  v1.1/deploy-cockroachdb-on-premises.md
  v1.1/generate-cockroachdb-resources.md
  v1.1/recommended-production-settings.md
  v1.1/upgrade-cockroach-version.md
  v2.0/deploy-cockroachdb-on-aws-insecure.md
  v2.0/deploy-cockroachdb-on-aws.md
  v2.0/deploy-cockroachdb-on-digital-ocean-insecure.md
  v2.0/deploy-cockroachdb-on-digital-ocean.md
  v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
  v2.0/deploy-cockroachdb-on-google-cloud-platform.md
  v2.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
  v2.0/deploy-cockroachdb-on-microsoft-azure.md
  v2.0/deploy-cockroachdb-on-premises-insecure.md
  v2.0/deploy-cockroachdb-on-premises.md
  v2.0/generate-cockroachdb-resources.md
  v2.0/recommended-production-settings.md
  v2.0/upgrade-cockroach-version.md
Labels: in progress

#2820 Partitioning individual doc updates
  _includes/sidebar-data-v2.0.json
  _includes/sql/v2.0/diagrams/alter_table_partition_by.html
  _includes/sql/v2.0/diagrams/create_table_partition_by.html
  _includes/sql/v2.0/diagrams/experimental_audit.html
  v2.0/alter-table.md
  v2.0/configure-replication-zones.md
  v2.0/create-table.md
  v2.0/partition-by.md
  v2.0/partitioning.md
Labels: in progress

#2825 Copy v1.0 known join flag limitation over to v1.1 known limitations
  v1.1/known-limitations.md
Labels: in progress

#2827 Enable feedback widget on exposed training pages
  v1.1/training/cluster-startup-and-scaling.md
  v1.1/training/fault-tolerance-and-automated-repair.md
  v1.1/training/index.md
  v1.1/training/locality-and-replication-zones.md
  v2.0/training/cluster-startup-and-scaling.md
  v2.0/training/fault-tolerance-and-automated-repair.md
  v2.0/training/index.md
  v2.0/training/locality-and-replication-zones.md
Labels: in progress

#2830 Change PushTxnQueue to TxnWaitQueue in 2.0 architecture docs
  v2.0/architecture/transaction-layer.md
Labels: in progress
